version: "4.27.2"
services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./task1:/task1
      - ./task2/task2b:/task2b
      - ./task2/task2a:/task2a
      - ./task2/task2c:/task2c
      - ./task3:/task3
      - ./site.conf:/etc/nginx/conf.d/site.conf
    links:
      - php
  php:
    image: php:8.3-fpm
    volumes:
      - ./task1:/task1
      - ./task2/task2b:/task2b
      - ./task2/task2a:/task2a
      - ./task2/task2c:/task2c
      - ./task3:/task3

